on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: CommunityPro
          label: i want to join the community 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<p><b>Invitation sent to join the Community</b></p> <b>Welcome to TechTrybe🎉 </b><br><br>Dont forget to make it public after accepting so it appears on your GitHub profile for everyone else to see. <br /><p>Remember contributing to open source is not just about code, its about collaboration, communication and adding value<br><b>Thank you and welcome to the community</b></p>'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
